### ISSUE TITLE
XSS Vulnerability

### ISSUE THREAD

**Issue by zxc7528064** [fredtempez/ZwiiCMS#8]
Hi ~ I find a XSS Vulnerability (Stored)
Version : 10.1.02
Author : Noth(沈彧璿)
Step 1 : login system
Step 2 : /zwiicms/?config/script/body ，XSS weakness in the "Editor de script dans Body" store.
![4](https://user-images.githubusercontent.com/45315211/83340264-85518700-a308-11ea-8542-6e555a3200a1.jpg)
Step 3 : Back to the front desk
![5](https://user-images.githubusercontent.com/45315211/83340268-94383980-a308-11ea-9993-d56ac08124dd.jpg)

**Comment by fredtempez** [comment]
Hello,
Dont thing so, because of step 1. If you do the same without being logged ok.

**Comment by zxc7528064** [comment]
@fredtempez  Hi~ After logging into the system，I find the security problem
Report this security problem, hope you can fix it . 
you can try php function like htmlspecialchar to fix it

**Comment by zxc7528064** [comment]
@fredtempez  If you think this is a security issue, can I apply for a CVE ID ? 
Best Regard

**Comment by fredtempez** [comment]
You are wrong, It's not a vulnerability cause your are login and you enter a script as an administrator.
Feel free to do the same without being connected and we will talk about.

**Comment by zxc7528064** [comment]
@fredtempez  This is a stored XSS, which means that the entry and exit points have not been encoded and escaped to cause this problem.

**Comment by zxc7528064** [comment]
@fredtempez  Close the issue ...
